spring:
  profiles:
    active: deleteMe

---
# Coloque aqui suas configurações de Desenvolvimento
spring:
  profiles: dev

---
# Coloque aqui suas configurações de Homologação
spring:
  profiles: homo

---
spring:
  profiles: deleteMe
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password